sudo: required
services: 
  - docker
env: 
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-412112 
  - gcloud config set compute/zone europe-north1-a 
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t Myhome210190/react-test -f ./client/Dockerfile.dev ./client

install:
  - curl https://pyenv.run | bash
  - export PATH="/home/travis/.pyenv/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"
  - pyenv install 3.10
  - pyenv global 3.10
  - python --version

script:
  - docker run -e CI=true Myhome210190/react-test npm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: master